# CMake generated Testfile for 
# Source directory: /home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_statistics/src/test
# Build directory: /home/zaina/catkin_ws/build_isolated/ecl_statistics/src/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_ecl_statistics_gtest_ecl_test_covariance_ellipsoids "/home/zaina/catkin_ws/build_isolated/ecl_statistics/catkin_generated/env_cached.sh" "/home/zaina/catkin_ws/venv/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/zaina/catkin_ws/build_isolated/ecl_statistics/test_results/ecl_statistics/gtest-ecl_test_covariance_ellipsoids.xml" "--return-code" "/home/zaina/catkin_ws/devel_isolated/ecl_statistics/lib/ecl_statistics/ecl_test_covariance_ellipsoids --gtest_output=xml:/home/zaina/catkin_ws/build_isolated/ecl_statistics/test_results/ecl_statistics/gtest-ecl_test_covariance_ellipsoids.xml")
set_tests_properties(_ctest_ecl_statistics_gtest_ecl_test_covariance_ellipsoids PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_statistics/src/test/CMakeLists.txt;6;catkin_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_statistics/src/test/CMakeLists.txt;16;ecl_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_statistics/src/test/CMakeLists.txt;0;")
add_test(_ctest_ecl_statistics_gtest_ecl_test_cumulative_statistics "/home/zaina/catkin_ws/build_isolated/ecl_statistics/catkin_generated/env_cached.sh" "/home/zaina/catkin_ws/venv/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/zaina/catkin_ws/build_isolated/ecl_statistics/test_results/ecl_statistics/gtest-ecl_test_cumulative_statistics.xml" "--return-code" "/home/zaina/catkin_ws/devel_isolated/ecl_statistics/lib/ecl_statistics/ecl_test_cumulative_statistics --gtest_output=xml:/home/zaina/catkin_ws/build_isolated/ecl_statistics/test_results/ecl_statistics/gtest-ecl_test_cumulative_statistics.xml")
set_tests_properties(_ctest_ecl_statistics_gtest_ecl_test_cumulative_statistics PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_statistics/src/test/CMakeLists.txt;6;catkin_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_statistics/src/test/CMakeLists.txt;17;ecl_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_statistics/src/test/CMakeLists.txt;0;")
