# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/zaina/catkin_ws/src/Turtlebot_on_noetic/kobuki_msgs/msg/BumperEvent.msg;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/kobuki_msgs/msg/CliffEvent.msg;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/kobuki_msgs/msg/DigitalOutput.msg;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/kobuki_msgs/msg/ExternalPower.msg;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/kobuki_msgs/msg/Led.msg;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/kobuki_msgs/msg/PowerSystemEvent.msg;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/kobuki_msgs/msg/SensorState.msg;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/kobuki_msgs/msg/VersionInfo.msg;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/kobuki_msgs/msg/ControllerInfo.msg;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/kobuki_msgs/msg/ButtonEvent.msg;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/kobuki_msgs/msg/DigitalInputEvent.msg;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/kobuki_msgs/msg/DockInfraRed.msg;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/kobuki_msgs/msg/KeyboardInput.msg;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/kobuki_msgs/msg/MotorPower.msg;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/kobuki_msgs/msg/RobotStateEvent.msg;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/kobuki_msgs/msg/Sound.msg;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/kobuki_msgs/msg/ScanAngle.msg;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/kobuki_msgs/msg/WheelDropEvent.msg;/home/zaina/catkin_ws/devel_isolated/kobuki_msgs/share/kobuki_msgs/msg/AutoDockingAction.msg;/home/zaina/catkin_ws/devel_isolated/kobuki_msgs/share/kobuki_msgs/msg/AutoDockingActionGoal.msg;/home/zaina/catkin_ws/devel_isolated/kobuki_msgs/share/kobuki_msgs/msg/AutoDockingActionResult.msg;/home/zaina/catkin_ws/devel_isolated/kobuki_msgs/share/kobuki_msgs/msg/AutoDockingActionFeedback.msg;/home/zaina/catkin_ws/devel_isolated/kobuki_msgs/share/kobuki_msgs/msg/AutoDockingGoal.msg;/home/zaina/catkin_ws/devel_isolated/kobuki_msgs/share/kobuki_msgs/msg/AutoDockingResult.msg;/home/zaina/catkin_ws/devel_isolated/kobuki_msgs/share/kobuki_msgs/msg/AutoDockingFeedback.msg"
services_str = ""
pkg_name = "kobuki_msgs"
dependencies_str = "std_msgs;actionlib_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "kobuki_msgs;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/kobuki_msgs/msg;kobuki_msgs;/home/zaina/catkin_ws/devel_isolated/kobuki_msgs/share/kobuki_msgs/msg;std_msgs;/opt/ros/noetic/share/std_msgs/cmake/../msg;actionlib_msgs;/opt/ros/noetic/share/actionlib_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/home/zaina/catkin_ws/venv/bin/python3"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/noetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
