# CMake generated Testfile for 
# Source directory: /home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_devices/src/test
# Build directory: /home/zaina/catkin_ws/build_isolated/ecl_devices/src/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_ecl_devices_gtest_ecl_test_shared_files "/home/zaina/catkin_ws/build_isolated/ecl_devices/catkin_generated/env_cached.sh" "/home/zaina/catkin_ws/venv/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/zaina/catkin_ws/build_isolated/ecl_devices/test_results/ecl_devices/gtest-ecl_test_shared_files.xml" "--return-code" "/home/zaina/catkin_ws/devel_isolated/ecl_devices/lib/ecl_devices/ecl_test_shared_files --gtest_output=xml:/home/zaina/catkin_ws/build_isolated/ecl_devices/test_results/ecl_devices/gtest-ecl_test_shared_files.xml")
set_tests_properties(_ctest_ecl_devices_gtest_ecl_test_shared_files PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_devices/src/test/CMakeLists.txt;6;catkin_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_devices/src/test/CMakeLists.txt;16;ecl_devices_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_devices/src/test/CMakeLists.txt;0;")
add_test(_ctest_ecl_devices_gtest_ecl_test_files "/home/zaina/catkin_ws/build_isolated/ecl_devices/catkin_generated/env_cached.sh" "/home/zaina/catkin_ws/venv/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/zaina/catkin_ws/build_isolated/ecl_devices/test_results/ecl_devices/gtest-ecl_test_files.xml" "--return-code" "/home/zaina/catkin_ws/devel_isolated/ecl_devices/lib/ecl_devices/ecl_test_files --gtest_output=xml:/home/zaina/catkin_ws/build_isolated/ecl_devices/test_results/ecl_devices/gtest-ecl_test_files.xml")
set_tests_properties(_ctest_ecl_devices_gtest_ecl_test_files PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_devices/src/test/CMakeLists.txt;6;catkin_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_devices/src/test/CMakeLists.txt;17;ecl_devices_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_devices/src/test/CMakeLists.txt;0;")
