set(_CATKIN_CURRENT_PACKAGE "turtlebot_obstacle_avoidance")
set(turtlebot_obstacle_avoidance_VERSION "0.0.0")
set(turtlebot_obstacle_avoidance_MAINTAINER "zaina <zaina@todo.todo>")
set(turtlebot_obstacle_avoidance_PACKAGE_FORMAT "2")
set(turtlebot_obstacle_avoidance_BUILD_DEPENDS "rospy" "sensor_msgs")
set(turtlebot_obstacle_avoidance_BUILD_EXPORT_DEPENDS "rospy" "sensor_msgs")
set(turtlebot_obstacle_avoidance_BUILDTOOL_DEPENDS "catkin")
set(turtlebot_obstacle_avoidance_BUILDTOOL_EXPORT_DEPENDS )
set(turtlebot_obstacle_avoidance_EXEC_DEPENDS "rospy" "sensor_msgs")
set(turtlebot_obstacle_avoidance_RUN_DEPENDS "rospy" "sensor_msgs")
set(turtlebot_obstacle_avoidance_TEST_DEPENDS )
set(turtlebot_obstacle_avoidance_DOC_DEPENDS )
set(turtlebot_obstacle_avoidance_URL_WEBSITE "")
set(turtlebot_obstacle_avoidance_URL_BUGTRACKER "")
set(turtlebot_obstacle_avoidance_URL_REPOSITORY "")
set(turtlebot_obstacle_avoidance_DEPRECATED "")