#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/zaina/catkin_ws/devel_isolated/ecl_converters:/home/zaina/catkin_ws/devel_isolated/ecl_concepts:/home/zaina/catkin_ws/devel_isolated/ecl_type_traits:/home/zaina/catkin_ws/devel_isolated/ecl_tools:/home/zaina/catkin_ws/devel_isolated/ecl_ipc:/home/zaina/catkin_ws/devel_isolated/ecl_time:/home/zaina/catkin_ws/devel_isolated/ecl_time_lite:/home/zaina/catkin_ws/devel_isolated/ecl_sigslots_lite:/home/zaina/catkin_ws/devel_isolated/ecl_navigation:/home/zaina/catkin_ws/devel_isolated/ecl_mpl:/home/zaina/catkin_ws/devel_isolated/ecl_lite:/home/zaina/catkin_ws/devel_isolated/ecl_io:/home/zaina/catkin_ws/devel_isolated/ecl_filesystem:/home/zaina/catkin_ws/devel_isolated/ecl_exceptions:/home/zaina/catkin_ws/devel_isolated/ecl_errors:/home/zaina/catkin_ws/devel_isolated/ecl_eigen:/home/zaina/catkin_ws/devel_isolated/ecl_converters_lite:/home/zaina/catkin_ws/devel_isolated/ecl_console:/home/zaina/catkin_ws/devel_isolated/ecl_config:/home/zaina/catkin_ws/devel_isolated/ecl_command_line:/home/zaina/catkin_ws/devel_isolated/ecl_build:/home/zaina/catkin_ws/devel_isolated/ecl_license:/home/zaina/catkin_ws/devel_isolated/ecl_core:/home/zaina/catkin_ws/devel_isolated/depthimage_to_laserscan:/home/zaina/catkin_ws/devel_isolated/beginner_tutorials:/opt/ros/noetic:/home/zaina/catkin_ws/devel_isolated/csm'
export LD_LIBRARY_PATH='/home/zaina/catkin_ws/devel_isolated/ecl_converters/lib:/home/zaina/catkin_ws/devel_isolated/ecl_concepts/lib:/home/zaina/catkin_ws/devel_isolated/ecl_type_traits/lib:/home/zaina/catkin_ws/devel_isolated/ecl_ipc/lib:/home/zaina/catkin_ws/devel_isolated/ecl_time/lib:/home/zaina/catkin_ws/devel_isolated/ecl_time_lite/lib:/home/zaina/catkin_ws/devel_isolated/ecl_sigslots_lite/lib:/home/zaina/catkin_ws/devel_isolated/ecl_mpl/lib:/home/zaina/catkin_ws/devel_isolated/ecl_io/lib:/home/zaina/catkin_ws/devel_isolated/ecl_filesystem/lib:/home/zaina/catkin_ws/devel_isolated/ecl_exceptions/lib:/home/zaina/catkin_ws/devel_isolated/ecl_errors/lib:/home/zaina/catkin_ws/devel_isolated/ecl_eigen/lib:/home/zaina/catkin_ws/devel_isolated/ecl_converters_lite/lib:/home/zaina/catkin_ws/devel_isolated/ecl_console/lib:/home/zaina/catkin_ws/devel_isolated/ecl_config/lib:/home/zaina/catkin_ws/devel_isolated/ecl_command_line/lib:/home/zaina/catkin_ws/devel_isolated/ecl_build/lib:/home/zaina/catkin_ws/devel_isolated/ecl_license/lib:/home/zaina/catkin_ws/devel_isolated/depthimage_to_laserscan/lib:/home/zaina/catkin_ws/devel_isolated/beginner_tutorials/lib:/opt/ros/noetic/lib:/home/zaina/catkin_ws/devel_isolated/csm/lib'
export PATH='/home/zaina/catkin_ws/devel_isolated/ecl_type_traits/bin:/home/zaina/catkin_ws/devel_isolated/ecl_config/bin:/opt/ros/noetic/bin:/home/zaina/catkin_ws/devel_isolated/csm/bin:/home/zaina/.vscode/extensions/ms-python.python-2024.4.1/python_files/deactivate/bash:/home/zaina/catkin_ws/venv/bin:/home/zaina/.vscode/extensions/ms-python.python-2024.4.1/python_files/deactivate/bash:/home/zaina/catkin_ws/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PKG_CONFIG_PATH='/home/zaina/catkin_ws/devel_isolated/ecl_converters/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/ecl_concepts/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/ecl_type_traits/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/ecl_ipc/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/ecl_time/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/ecl_time_lite/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/ecl_sigslots_lite/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/ecl_mpl/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/ecl_io/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/ecl_filesystem/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/ecl_exceptions/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/ecl_errors/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/ecl_eigen/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/ecl_converters_lite/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/ecl_console/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/ecl_config/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/ecl_command_line/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/ecl_build/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/ecl_license/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/depthimage_to_laserscan/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/beginner_tutorials/lib/pkgconfig:/opt/ros/noetic/lib/pkgconfig:/home/zaina/catkin_ws/devel_isolated/csm/lib/pkgconfig'
export ROS_PACKAGE_PATH="/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_converters:$ROS_PACKAGE_PATH"