# CMake generated Testfile for 
# Source directory: /home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_streams/src/test
# Build directory: /home/zaina/catkin_ws/build_isolated/ecl_streams/src/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_ecl_streams_gtest_ecl_test_file_streams "/home/zaina/catkin_ws/build_isolated/ecl_streams/catkin_generated/env_cached.sh" "/home/zaina/catkin_ws/venv/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/zaina/catkin_ws/build_isolated/ecl_streams/test_results/ecl_streams/gtest-ecl_test_file_streams.xml" "--return-code" "/home/zaina/catkin_ws/devel_isolated/ecl_streams/lib/ecl_streams/ecl_test_file_streams --gtest_output=xml:/home/zaina/catkin_ws/build_isolated/ecl_streams/test_results/ecl_streams/gtest-ecl_test_file_streams.xml")
set_tests_properties(_ctest_ecl_streams_gtest_ecl_test_file_streams PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_streams/src/test/CMakeLists.txt;7;catkin_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_streams/src/test/CMakeLists.txt;14;ecl_streams_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_streams/src/test/CMakeLists.txt;0;")
add_test(_ctest_ecl_streams_gtest_ecl_test_string_streams "/home/zaina/catkin_ws/build_isolated/ecl_streams/catkin_generated/env_cached.sh" "/home/zaina/catkin_ws/venv/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/zaina/catkin_ws/build_isolated/ecl_streams/test_results/ecl_streams/gtest-ecl_test_string_streams.xml" "--return-code" "/home/zaina/catkin_ws/devel_isolated/ecl_streams/lib/ecl_streams/ecl_test_string_streams --gtest_output=xml:/home/zaina/catkin_ws/build_isolated/ecl_streams/test_results/ecl_streams/gtest-ecl_test_string_streams.xml")
set_tests_properties(_ctest_ecl_streams_gtest_ecl_test_string_streams PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_streams/src/test/CMakeLists.txt;7;catkin_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_streams/src/test/CMakeLists.txt;15;ecl_streams_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_streams/src/test/CMakeLists.txt;0;")
