set(_CATKIN_CURRENT_PACKAGE "obstacle-avoidance-turtlebot")
set(obstacle-avoidance-turtlebot_VERSION "0.0.0")
set(obstacle-avoidance-turtlebot_MAINTAINER "Sadman Sakib Enan <sadmansakib.enan@gmail.com>")
set(obstacle-avoidance-turtlebot_PACKAGE_FORMAT "2")
set(obstacle-avoidance-turtlebot_BUILD_DEPENDS "rospy")
set(obstacle-avoidance-turtlebot_BUILD_EXPORT_DEPENDS "rospy")
set(obstacle-avoidance-turtlebot_BUILDTOOL_DEPENDS "catkin")
set(obstacle-avoidance-turtlebot_BUILDTOOL_EXPORT_DEPENDS )
set(obstacle-avoidance-turtlebot_EXEC_DEPENDS "rospy")
set(obstacle-avoidance-turtlebot_RUN_DEPENDS "rospy")
set(obstacle-avoidance-turtlebot_TEST_DEPENDS )
set(obstacle-avoidance-turtlebot_DOC_DEPENDS )
set(obstacle-avoidance-turtlebot_URL_WEBSITE "https://github.com/enansakib/obstacle-avoidance-turtlebot.git")
set(obstacle-avoidance-turtlebot_URL_BUGTRACKER "")
set(obstacle-avoidance-turtlebot_URL_REPOSITORY "")
set(obstacle-avoidance-turtlebot_DEPRECATED "")