# CMake generated Testfile for 
# Source directory: /home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test
# Build directory: /home/zaina/catkin_ws/build_isolated/ecl_time/src/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_ecl_time_gtest_ecl_test_cpuwatch_rt "/home/zaina/catkin_ws/build_isolated/ecl_time/catkin_generated/env_cached.sh" "/home/zaina/catkin_ws/venv/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/zaina/catkin_ws/build_isolated/ecl_time/test_results/ecl_time/gtest-ecl_test_cpuwatch_rt.xml" "--return-code" "/home/zaina/catkin_ws/devel_isolated/ecl_time/lib/ecl_time/ecl_test_cpuwatch_rt --gtest_output=xml:/home/zaina/catkin_ws/build_isolated/ecl_time/test_results/ecl_time/gtest-ecl_test_cpuwatch_rt.xml")
set_tests_properties(_ctest_ecl_time_gtest_ecl_test_cpuwatch_rt PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;6;catkin_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;17;ecl_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;0;")
add_test(_ctest_ecl_time_gtest_ecl_test_frequency "/home/zaina/catkin_ws/build_isolated/ecl_time/catkin_generated/env_cached.sh" "/home/zaina/catkin_ws/venv/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/zaina/catkin_ws/build_isolated/ecl_time/test_results/ecl_time/gtest-ecl_test_frequency.xml" "--return-code" "/home/zaina/catkin_ws/devel_isolated/ecl_time/lib/ecl_time/ecl_test_frequency --gtest_output=xml:/home/zaina/catkin_ws/build_isolated/ecl_time/test_results/ecl_time/gtest-ecl_test_frequency.xml")
set_tests_properties(_ctest_ecl_time_gtest_ecl_test_frequency PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;6;catkin_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;18;ecl_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;0;")
add_test(_ctest_ecl_time_gtest_ecl_test_sleep "/home/zaina/catkin_ws/build_isolated/ecl_time/catkin_generated/env_cached.sh" "/home/zaina/catkin_ws/venv/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/zaina/catkin_ws/build_isolated/ecl_time/test_results/ecl_time/gtest-ecl_test_sleep.xml" "--return-code" "/home/zaina/catkin_ws/devel_isolated/ecl_time/lib/ecl_time/ecl_test_sleep --gtest_output=xml:/home/zaina/catkin_ws/build_isolated/ecl_time/test_results/ecl_time/gtest-ecl_test_sleep.xml")
set_tests_properties(_ctest_ecl_time_gtest_ecl_test_sleep PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;6;catkin_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;19;ecl_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;0;")
add_test(_ctest_ecl_time_gtest_ecl_test_snooze "/home/zaina/catkin_ws/build_isolated/ecl_time/catkin_generated/env_cached.sh" "/home/zaina/catkin_ws/venv/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/zaina/catkin_ws/build_isolated/ecl_time/test_results/ecl_time/gtest-ecl_test_snooze.xml" "--return-code" "/home/zaina/catkin_ws/devel_isolated/ecl_time/lib/ecl_time/ecl_test_snooze --gtest_output=xml:/home/zaina/catkin_ws/build_isolated/ecl_time/test_results/ecl_time/gtest-ecl_test_snooze.xml")
set_tests_properties(_ctest_ecl_time_gtest_ecl_test_snooze PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;6;catkin_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;20;ecl_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;0;")
add_test(_ctest_ecl_time_gtest_ecl_test_timestamp "/home/zaina/catkin_ws/build_isolated/ecl_time/catkin_generated/env_cached.sh" "/home/zaina/catkin_ws/venv/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/zaina/catkin_ws/build_isolated/ecl_time/test_results/ecl_time/gtest-ecl_test_timestamp.xml" "--return-code" "/home/zaina/catkin_ws/devel_isolated/ecl_time/lib/ecl_time/ecl_test_timestamp --gtest_output=xml:/home/zaina/catkin_ws/build_isolated/ecl_time/test_results/ecl_time/gtest-ecl_test_timestamp.xml")
set_tests_properties(_ctest_ecl_time_gtest_ecl_test_timestamp PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;6;catkin_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;21;ecl_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;0;")
add_test(_ctest_ecl_time_gtest_ecl_test_time_data "/home/zaina/catkin_ws/build_isolated/ecl_time/catkin_generated/env_cached.sh" "/home/zaina/catkin_ws/venv/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/zaina/catkin_ws/build_isolated/ecl_time/test_results/ecl_time/gtest-ecl_test_time_data.xml" "--return-code" "/home/zaina/catkin_ws/devel_isolated/ecl_time/lib/ecl_time/ecl_test_time_data --gtest_output=xml:/home/zaina/catkin_ws/build_isolated/ecl_time/test_results/ecl_time/gtest-ecl_test_time_data.xml")
set_tests_properties(_ctest_ecl_time_gtest_ecl_test_time_data PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;6;catkin_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;22;ecl_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;0;")
add_test(_ctest_ecl_time_gtest_ecl_test_stopwatch "/home/zaina/catkin_ws/build_isolated/ecl_time/catkin_generated/env_cached.sh" "/home/zaina/catkin_ws/venv/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/zaina/catkin_ws/build_isolated/ecl_time/test_results/ecl_time/gtest-ecl_test_stopwatch.xml" "--return-code" "/home/zaina/catkin_ws/devel_isolated/ecl_time/lib/ecl_time/ecl_test_stopwatch --gtest_output=xml:/home/zaina/catkin_ws/build_isolated/ecl_time/test_results/ecl_time/gtest-ecl_test_stopwatch.xml")
set_tests_properties(_ctest_ecl_time_gtest_ecl_test_stopwatch PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;6;catkin_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;23;ecl_add_gtest;/home/zaina/catkin_ws/src/Turtlebot_on_noetic/ecl_core/ecl_time/src/test/CMakeLists.txt;0;")
